### ISSUE TITLE
undefined funciton nil.get_by/2

### ISSUE THREAD

**Issue by joshuaswilcox** [opendrops/passport#22] opened 2016-03-04 12:41 UTC
when trying to login I get this

```
[error] #PID<0.525.0> running Scotchy.Endpoint terminated
Server: localhost:4000 (http)
Request: POST /login
** (exit) an exception was raised:
    ** (UndefinedFunctionError) undefined function nil.get_by/2
        nil.get_by(nil, [email: "*****"])
        lib/passport/session.ex:17: Passport.Session.login/3
        (scotchy) web/controllers/session_controller.ex:14: Scotchy.SessionController.create/2
        (scotchy) web/controllers/session_controller.ex:1: Scotchy.SessionController.action/2
        (scotchy) web/controllers/session_controller.ex:1:     Scotchy.SessionController.phoenix_controller_pipeline/2
        (scotchy) lib/phoenix/router.ex:261: Scotchy.Router.dispatch/2
        (scotchy) web/router.ex:1: Scotchy.Router.do_call/2
        (scotchy) lib/scotchy/endpoint.ex:1: Scotchy.Endpoint.phoenix_pipeline/1
        (scotchy) lib/plug/debugger.ex:93: Scotchy.Endpoint."call (overridable 3)"/2
        (scotchy) lib/phoenix/endpoint/render_errors.ex:34: Scotchy.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

Not sure what the issue is, i followed the setup instructions

**Comment by artyomkalm** [comment] 2016-03-05 06:34
I get the same

**Comment by stvn** [comment] 2016-03-12 23:36
Also encountering the same issue.  Anyone have any luck?

**Comment by stvn** [comment] 2016-03-13 06:30
I was able to resolve my problem by doing a few of things --- 1) i modified the position of my config :passport entry in my config.exs by moving it to the top of the module (instead of bottom) -- i'm not sure that this actually resolved it but adding it incase it helps anyone else -- 2) ran `mix clean --deps` to delete my _build/libs/passport dir.  3) ran `mix deps.get` and started server.  Everything is now working.  No error.

**Comment by joshuaswilcox** [comment] 2016-03-15 16:15
@stvn i'll have to give that a try, thanks!

**Comment by fmeyer** [comment] 2016-04-19 21:45
I can confirm that @stvn solution works for me too.

**Comment by tronathan** [comment] 2016-05-03 03:47
I can also confirm that @stvn solution worked. The extra steps of cleaning dependencies, deleting the `_build/libs/passport`, and reinstalling dependencies *is* necessary. Restated for clarity:

1) Move position of my config :passport entry in my config.exs to the top
2) run:
```
mix clean --deps
rm -rf _build/libs/passport
mix deps.get
```

That does the trick.

**Comment by fmounir** [comment] 2016-05-17 14:27
@stvn  your solution worked for me :) thanks :+1:

**Comment by loongmxbt** [comment] 2016-05-18 05:59
Works for me, but why..

**Comment by fmounir** [comment] 2016-05-18 20:39
@loongmxbt can you please share code snippet how to get current user in the controller ?

**Comment by fmounir** [comment] 2016-05-18 22:34
Sorry wrong thread

**Comment by shankardevy** [comment] 2017-03-06 04:44
Passport is now Phoenix 1.3 ready and has gone a full rewrite. Please check the latest master. Closing this.

**Closed by shankardevy** 2017-03-06 04:44 UTC
